"""Generate ssi263_defaults.h: the chip's default parameters and ROM, for front ends with no Python (the Linux
module, Android).  Python stays the reference: the values come from ssi263/params.py (Params()) through
native.params_struct, and the ROM from Rom.load() through native.rom_bytes -- the same path the add-ons take.

    python src/csrc/gen_chip_defaults.py          # rewrite the header
    python src/csrc/gen_chip_defaults.py --check  # exit 1 if the header is stale (run_tests)

ssi263_params is all doubles in the header's order, so the defaults are one flat double array on every platform.
repr() gives the shortest decimal that reads back as the same double, and C compilers round decimal literals
correctly, so the array is exact (the drift test compares the bytes).
"""
import os
import sys
from array import array

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from ssi263.native import params_struct, rom_bytes   # noqa: E402
from ssi263.params import Params                      # noqa: E402
from ssi263.rom import Rom                            # noqa: E402

OUT = os.path.join(HERE, "ssi263_defaults.h")


def values():
    d = array("d")
    d.frombytes(bytes(params_struct(Params())))
    return list(d), rom_bytes(Rom.load())


def render():
    d, rom = values()
    lines = ["/* Generated by gen_chip_defaults.py from ssi263/params.py and the ROM: do not edit. */",
             "#ifndef SSI263_DEFAULTS_H", "#define SSI263_DEFAULTS_H", "",
             "#define SSI263_DEFAULT_PARAMS_N %d" % len(d), "",
             "static const double ssi263_default_params_d[SSI263_DEFAULT_PARAMS_N] = {"]
    for i in range(0, len(d), 4):
        lines.append("    " + " ".join("%s," % repr(float(v)) for v in d[i:i + 4]))
    lines += ["};", "", "static const unsigned char ssi263_default_rom_d[%d] = {" % len(rom)]
    for i in range(0, len(rom), 9):
        lines.append("    " + " ".join("%d," % b for b in rom[i:i + 9]))
    lines += ["};", "", "#endif", ""]
    return "\n".join(lines)


def main():
    text = render()
    old = open(OUT, encoding="utf-8").read() if os.path.isfile(OUT) else None
    if "--check" in sys.argv:
        if old != text:
            print("ssi263_defaults.h is stale: run python src/csrc/gen_chip_defaults.py")
            sys.exit(1)
        # and the compiled chip hands out exactly those bytes (the literals parsed back to the same doubles)
        import ctypes
        from ssi263 import dsp
        lib = ctypes.CDLL(dsp.lib_path())
        n = lib.ssi263_params_size()
        buf = ctypes.create_string_buffer(n)
        lib.ssi263_default_params(buf)
        lib.ssi263_default_rom.restype = ctypes.POINTER(ctypes.c_ubyte * 576)
        d, rom = values()
        if buf.raw != array("d", d).tobytes() or bytes(lib.ssi263_default_rom().contents) != rom:
            print("the compiled chip's defaults differ from params.py / the ROM: rebuild it (build_native.py)")
            sys.exit(1)
        print("ssi263_defaults.h and the compiled chip match params.py and the ROM (%d params)" % len(d))
        return
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s (%d params, %d ROM bytes)" % (OUT, *(lambda d, r: (len(d), len(r)))(*values())))


if __name__ == "__main__":
    main()
