"""Generate bl_whine_table.h from src/hosts/blazie.py's WHINE_TONES (the measured per-tone line levels), so the C
host carries exactly the Python host's data.  python src/csrc/blazie/gen_whine.py"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(os.path.dirname(HERE)))
from hosts import blazie as B  # noqa: E402

out = ["/* Generated by gen_whine.py from src/hosts/blazie.py WHINE_TONES -- do not edit.  Per class (hiss, whine) and",
       " * tone 0..26: the measured comb lines, \"n:dB ...\" (line n x fc/64, dB re a loud vowel's mean square). */",
       "#define BL_WHINE_VOWEL_RMS %r" % B.WHINE_VOWEL_RMS,
       "#define BL_WHINE_TABLE %d" % B.WHINE_TABLE,
       "#define BL_WHINE_SEED %dU" % B.WHINE_SEED,
       "static const char *const BL_WHINE_TONES[2][27] = {"]
for mode in ("hiss", "whine"):
    rows = B.WHINE_TONES[mode]
    assert len(rows) == 27
    out.append("    {   /* %s */" % mode)
    for t, r in enumerate(rows):
        out.append('        "%s",   /* tone %d */' % (r, t))
    out.append("    },")
out.append("};")
open(os.path.join(HERE, "bl_whine_table.h"), "w", encoding="ascii", newline="\n").write("\n".join(out) + "\n")
print("wrote bl_whine_table.h")
