"""Generate bl_cp850.h and bl_cp852.h: bytes 0x80-0xFF of DOS code pages 850 and 852 as Python's codecs decode
them.  850 for bl_voice.c (the Spanish Braille Lite reads cp850: the NVDA driver encodes its text with Python's
"cp850") and the units' file names (bl_files_xfer.c); 852 for the Slovak Braille 'n Speak 2000's file names (its
firmware's own folder names are cp852: "fle\\xE7 s\\xA3bory", flash files).

    python gen_cp850.py           # rewrite the headers
    python gen_cp850.py --check   # exit 1 if one is stale (run_tests)
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PAGES = ("850", "852")


def render(page):
    cps = [ord(bytes([b]).decode("cp" + page)) for b in range(0x80, 0x100)]
    guard = "BL_CP%s_H" % page
    lines = ["/* Generated by gen_cp850.py from Python's cp%s codec: do not edit. */" % page,
             "#ifndef " + guard, "#define " + guard, "",
             "/* the code point of each byte 0x80 + i */",
             "static const unsigned short bl_cp%s_high[128] = {" % page]
    for i in range(0, 128, 8):
        lines.append("    " + " ".join("0x%04X," % c for c in cps[i:i + 8]))
    lines += ["};", "", "#endif", ""]
    return "\n".join(lines)


def main():
    stale = 0
    for page in PAGES:
        out = os.path.join(HERE, "bl_cp%s.h" % page)
        text = render(page)
        old = open(out, encoding="utf-8").read() if os.path.isfile(out) else None
        if "--check" in sys.argv:
            if old != text:
                print("bl_cp%s.h is stale: run python src/csrc/blazie/gen_cp850.py" % page)
                stale = 1
            else:
                print("bl_cp%s.h matches Python's cp%s" % (page, page))
            continue
        with open(out, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("wrote %s" % out)
    if stale:
        sys.exit(1)


if __name__ == "__main__":
    main()
