"""Generate bl_cp850.h: bytes 0x80-0xFF of DOS code page 850 as Python's codec decodes them, for bl_voice.c (the
Spanish Braille Lite reads cp850: the NVDA driver encodes its text with Python's "cp850").

    python gen_cp850.py           # rewrite the header
    python gen_cp850.py --check   # exit 1 if it is stale (run_tests)
"""
import os
import sys

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "bl_cp850.h")


def render():
    cps = [ord(bytes([b]).decode("cp850")) for b in range(0x80, 0x100)]
    lines = ["/* Generated by gen_cp850.py from Python's cp850 codec: do not edit. */",
             "#ifndef BL_CP850_H", "#define BL_CP850_H", "",
             "/* the code point of each byte 0x80 + i */",
             "static const unsigned short bl_cp850_high[128] = {"]
    for i in range(0, 128, 8):
        lines.append("    " + " ".join("0x%04X," % c for c in cps[i:i + 8]))
    lines += ["};", "", "#endif", ""]
    return "\n".join(lines)


def main():
    text = render()
    old = open(OUT, encoding="utf-8").read() if os.path.isfile(OUT) else None
    if "--check" in sys.argv:
        if old != text:
            print("bl_cp850.h is stale: run python src/csrc/blazie/gen_cp850.py")
            sys.exit(1)
        print("bl_cp850.h matches Python's cp850")
        return
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s" % OUT)


if __name__ == "__main__":
    main()
