"""Generate bl_idle_table.h from src/hosts/blazie_idle.py (the idle channel measured on Tomi's unit), so the C model
carries exactly those numbers.  python src/csrc/blazie/gen_idle.py [--check]"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(os.path.dirname(HERE)))
from hosts import blazie_idle as B  # noqa: E402


def text():
    out = ["/* Generated by gen_idle.py from src/hosts/blazie_idle.py -- do not edit.  Levels re the unit's volume-6 loud",
           " * vowel (REF): amplitudes as a ratio to its RMS, lines and the noise density in dB re its mean square. */",
           "#define BLI_REF_RMS %r" % B.REF_RMS,
           "#define BLI_NOISE_DB %r" % B.NOISE[0],
           "#define BLI_NOISE_POLE1 %r" % B.NOISE[1],
           "#define BLI_NOISE_POLE2 %r" % B.NOISE[2],
           "static const double BLI_POP[5] = {%s};" % ", ".join(repr(v) for v in B.POP),
           "static const double BLI_CLICK[3] = {%s};" % ", ".join(repr(v) for v in B.CLICK),
           "#define BLI_TICK_PERIOD_S %r" % B.TICK_PERIOD_S,
           "#define BLI_TICK_LEAD_S %r" % B.TICK_LEAD_S,
           "#define BLI_TICK_RATE %d" % B.TICK_RATE,
           "#define BLI_TICK_FADE_S %r" % B.TICK_FADE_S,
           "#define BLI_TICK_LEN %d" % len(B.TICK),
           "static const double BLI_TICK[%d] = {" % len(B.TICK)]
    vals = ["%r" % v for v in B.TICK]
    for i in range(0, len(vals), 8):
        out.append("    " + ", ".join(vals[i:i + 8]) + ",")
    out += ["};", "#define BLI_LINE_SEED %dU" % B.LINE_SEED, "static const char *const BLI_LINES[2][27] = {"]
    for mode in ("hiss", "whine"):
        rows = B.LINES[mode]
        assert len(rows) == 27
        out.append("    {   /* %s */" % mode)
        for t, r in enumerate(rows):
            out.append('        "%s",   /* tone %d */' % (r, t))
        out.append("    },")
    out.append("};")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    path = os.path.join(HERE, "bl_idle_table.h")
    if "--check" in sys.argv:
        with open(path, encoding="ascii") as f:
            ok = f.read() == text()
        print("bl_idle_table.h %s blazie_idle.py" % ("matches" if ok else "DIFFERS from"))
        sys.exit(0 if ok else 1)
    with open(path, "w", encoding="ascii", newline="\n") as f:
        f.write(text())
    print("wrote bl_idle_table.h")
