"""Generate z180_mame_machine.cpp from MAME's z180.cpp: the machine-level functions this library needs, copied from
exact upstream line ranges, with the framework calls replaced by named substitutions (each listed below and marked
'CHANGED' in the output).  Re-run it against a MAME checkout to update; it refuses to run if an anchor line has moved.

    python src/csrc/cpu/extract_z180_machine.py <mame checkout>

The upstream file is BSD-3-Clause (copyright-holders: Juergen Buchmueller); the generated file keeps that notice.
What is left out: the MAME device framework (configuration, save states, the debugger's state table, the
disassembler, execute_run -- replaced by our own step driver in z180_mame.cpp, see CONTRACT.md) and the file-level
flag tables, which z180_mame.hpp declares as class members under the same names (no statics: CONTRACT.md).
"""
import os
import sys

MAME = sys.argv[1]
SRC = os.path.join(MAME, "src", "devices", "cpu", "z180", "z180.cpp")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "z180_mame_machine.cpp")

# (first line, last line, the text that must open the range, what it is); line numbers as sed and grep count them
RANGES = [
    (89, 102, "/* interrupt priorities */", "interrupt priorities"),
    (169, 197, "#define CF  0x01", "flag bits and the I/O line bits"),
    (199, 207, "bool z180_device::get_tend0()", "the /TEND outputs"),
    (209, 258, "/*", "the register-name macros"),
    (259, 363, "#define Z180_TCR_TIF1           0x80", "the internal registers' bit definitions"),
    (364, 377, "/****", "the CPU prefixes (z180tbl.h depends on this order)"),
    (422, 1096, "uint8_t z180_device::z180_readcontrol(offs_t port)",
     "the internal registers, read and write (Z8S180's extra ones included: the firmware probes CCR)"),
    (1098, 1333, "int z180_device::z180_dma0(int max_cycles)", "the two DMA channels"),
    (1334, 1457, "void z180_device::z180_write_iolines(uint32_t data)", "the I/O lines"),
    (1458, 1536, "void z180_device::device_start()", "the flag tables (device_start's table part)"),
    (1681, 1751, "/****", "reset"),
    (1771, 1778, "void z8s180_device::device_reset()", "the Z8S180's reset"),
    (1789, 1887, "void z180_device::clock_timers()", "the timers, the interrupt check, the timer clocking"),
    (2043, 2077, "void z180_device::execute_set_input(int irqline, int state)", "the input lines"),
]

# after these ranges, lines of our own
AFTER = {
    (364, 377): ["", "// ---- the vendored instruction core (mame_z180/, unchanged) " + "-" * 44,
                 '#include "mame_z180/z180ops.h"', '#include "mame_z180/z180tbl.h"',
                 "", '#include "mame_z180/z180cb.hxx"', '#include "mame_z180/z180xy.hxx"',
                 '#include "mame_z180/z180dd.hxx"', '#include "mame_z180/z180fd.hxx"',
                 '#include "mame_z180/z180ed.hxx"', '#include "mame_z180/z180op.hxx"'],
    (1458, 1536): ["}   // CHANGED: closes init_tables(); upstream's device_start goes on with framework set-up"],
}

# (upstream text, replacement, why) -- applied to the copied text only; each must match exactly once
SUBS = [
    ("void z180_device::device_start()\n{",
     "void z180_device::init_tables()   // CHANGED: was device_start(); only its flag-table part is kept\n{",
     "device_start"),
]


def main():
    # split on newlines only, as sed and grep count lines (splitlines() also splits on other control characters)
    lines = [l.rstrip("\r") for l in open(SRC, encoding="utf-8", newline="").read().split("\n")]
    head = lines[0:2]
    assert head[0] == "// license:BSD-3-Clause", head
    out = head + [
        "//",
        "// z180_mame_machine.cpp -- GENERATED by extract_z180_machine.py from MAME's src/devices/cpu/z180/z180.cpp",
        "// (the revision in mame_z180/PINNED.txt).  The machine-level parts of MAME's Z180, copied from exact line",
        "// ranges; framework calls replaced as marked 'CHANGED'.  Do not edit: change the script and regenerate.",
        "// The class it compiles against: z180_mame.hpp.  Our step driver and the cpu.h API: z180_mame.cpp.  The",
        "// instruction bodies: mame_z180/ (unchanged).",
        "",
        '#include "z180_mame.hpp"',
    ]
    for a, b, opener, what in RANGES:
        seg = lines[a - 1:b]
        assert seg[0].strip().startswith(opener.strip()), "line %d moved: %r" % (a, seg[0])
        out.append("")
        out.append("// ---- upstream z180.cpp lines %d-%d: %s " % (a, b, what) + "-" * max(0, 60 - len(what)))
        out.extend(seg)
        out.extend(AFTER.get((a, b), []))
    text = "\n".join(out) + "\n"
    for old, new, why in SUBS:
        assert text.count(old) == 1, "substitution anchor not found exactly once: %s" % why
        text = text.replace(old, new)
    open(OUT, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote %s (%d lines from %d upstream ranges)" % (os.path.basename(OUT), text.count("\n"), len(RANGES)))


if __name__ == "__main__":
    main()
