// v40_mame.cpp -- cpu.h's V40 on MAME's NEC core: the CORRECTED path (CONTRACT.md 1-2, 4-7, 9, 12).
//
// One translation unit: MAME's code (v40_mame_machine.cpp, generated by extract_v40_machine.py) is included here.
// Build this file; never v40_mame_machine.cpp alone.
//
// The V40 is MAME's v40_device minus its peripherals: nec_common_device with an 8-bit bus, a 4-byte prefetch queue
// filled at 4 clocks a byte, V20_TYPE clock counts and no DIV quirk (v5x.cpp at the pinned revision, lines 572 and
// 584).  The on-chip ICU, TCU, SCU and DMA are the board's (cpu.h).
//
// The driver is ours.  It follows MAME's execute_run one step at a time, in the contract's phases:
//   A  execute_run's dispatch, with NEC's deferrals (drv_accept): with an interrupt pending and no shadow
//      (m_no_interrupt: after a move to or from a segment register, POP sreg, a completed POLL or LOCK), NMI always,
//      INT when IE is set and EI's delay (drv_ei_shadow) is not running -> external_int (MAME's nec_interrupt: PUSHF,
//      IE and BRK cleared, the vector number from bus.irq_ack for INT, CS and IP pushed, the vector loaded).  An
//      acceptance ends HALT; a halted core with an INT pending and IE = 0 is released without one.  v40_pc() is the
//      interrupted address: where execution resumes, the IP that is pushed.
//   B  its clocks: MAME charges 12, its PUSHF's (V20 count) -- nec_interrupt charges nothing of its own.  That is NOT
//      the V40's interrupt response time, which no source here gives (CONTRACT.md 12).
//   C  the shadows run down (execute_run: m_no_interrupt--; EI's drv_ei_shadow likewise).
//   D  steps++, the step's start (MAME's m_prev_ip), bus->boundary.
//   E  one instruction -- a prefix and its instruction are one step, as in MAME, which runs the prefixed handler from
//      the prefix's -- or one iteration of a REP string instruction, or a HALT slot of 2 clocks (model).
//   F  its clocks, the prefetch queue's accounting included (do_prefetch).  (No on-chip peripherals: G is empty.)
//
// REP: MAME runs a REP string instruction while its slice has clocks left (m_icount > 0), then leaves it pending
// (m_rep_params) with IP put back on the first prefix, and continues it at the next slice (cont_rep).  Here every
// step gives the instruction 1 clock, so each step is exactly one iteration: an interrupt is sampled between any two
// iterations, as NEC's chips take one there.  Acceptance clears the pending REP (nec_interrupt: m_rep_params = 0) and
// pushes the first prefix's address with CW, IX and IY as far as they got, so IRET re-executes the whole prefixed
// instruction -- a segment override included, before or after the REP -- for the iterations left.  Without an
// interrupt the override is carried from step to step (m_rep_params bit 2).
//
// Differences from MAME, each deliberate (the generated file marks those made there 'CHANGED'):
//   - Interrupts are sampled at every step's A (MAME: at each instruction of a slice, but a REP runs on to the
//     slice's end).  One REP iteration per step (above).
//   - A continued REP is not charged the prefix's 2 clocks again: MAME charges them at each re-entry, which with one
//     iteration per step would be every iteration.  A REP of n iterations costs what MAME charges in one slice.
//   - HALT: a slot is 2 clocks with no fetch (MAME ends its slice).  HALT is released at a step's A, never mid-step
//     at the line (MAME releases it at the line, so the instruction after the HLT ran before the interrupt): by an
//     acceptance, or, for an INT while IE = 0, without one -- the instruction after the HLT runs next and the INT
//     waits for IE (NEC's V40 data book, 1990, printed p.34).  The release costs no clocks (model: no figure).
//   - NEC's deferrals MAME lacks (after Astra, Reply 103): EI delays INT, not NMI, through the next instruction; a
//     move FROM a segment register, POP DS0/DS1 and a completed POLL defer NMI and INT like MAME's MOV/POP SS.
//   - The 8080 emulation mode (BRKEM) is not built: entering it sets v40_regs.fault and the core then does 2-clock
//     slots, nothing else.  No firmware here uses it.
//   - logerror's undefined and unimplemented opcodes are counted (v40_regs.undefined); MAME only logs them.  They
//     execute as MAME executes them (0x63, 0x66, 0x67, 0xF1: 10 clocks, nothing else; SETALC sets AL; ...).
//   - Reset keeps the lines: a held INT is asserted again (MAME's reset forgets it), a held NMI is no new edge.
// Kept from MAME, and stated because another core differs: the INT request is consumed by its acceptance
// (external_int clears the line), so a board asserts it again for a further request.
// Known limits: MAME's clock counts (its own "99% accurate"), its prefetch model, no bus-cycle placement of accesses
// (CONTRACT.md 7).
#include "v40_mame_machine.cpp"

#include <cstdarg>
#include <new>

static const int V40_HALT_SLOT = 2;          // clocks per HALT (or fault) slot (CONTRACT.md 6, model)
static const int V40_REP_PREFIX = 2;         // the REP prefix's clocks: do_rep*'s CLK(2), charged once per REP
static const int V40_STEP_ICOUNT = 1;        // the clocks a step gives an instruction: a REP stops after one iteration

// ---- the class's constructor: v5x.cpp's v40_device ---------------------------------------------------------------
nec_common_device::nec_common_device(const cpu_bus *bus)
    : v40_shim(bus),
      m_prefetch_size(4),                    // v40_device: v50_base_device(..., false, 4, 4, V20_TYPE)
      m_prefetch_cycles(4),
      m_chip_type(V20_TYPE),
      m_has_div_quirk(false)                 // v50_base_device passes false
{
    m_program = &m_space;
    m_dr8 = v40_opcodes{bus};
    m_xa = false;
    memset(m_v33_transtable, 0, sizeof m_v33_transtable);
    drv_undefined = drv_undefined_at = 0;
    drv_fault = false;
    drv_ei_shadow = 0;
    nec_popa_tmp = 0;
    m_pending_irq = m_nmi_state = m_irq_state = 0;
    m_poll_state = 1;
    m_halted = 0;
    m_rep_params = 0;
    m_icount = 0;
}

// ---- the driver's pieces, as members ---------------------------------------------------------------------------

u16 nec_common_device::drv_psw() { return CompressFlags(); }

// logerror: MAME's messages for an opcode it does not define or implement.  Counted; the rest (warnings, CHKIND's
// trace, the FPO escape, which is defined: it is the coprocessor's) are not.
void nec_common_device::drv_logerror(const char *fmt, ...)
{
    static const char *const undefined[] = {"ndefined", "nvalid", "nknown", "nimplemented mod", "XA instruction",
                                            "not supported on V33"};
    for (const char *u : undefined)
        if (strstr(fmt, u)) {
            drv_undefined++;
            drv_undefined_at = ((Sreg(PS) << 4) + m_prev_ip) & V40_ADDR_MASK;
            return;
        }
}

// Phase A.  NEC (V40 data book, 1990, printed p.34): NMI and an enabled INT are taken at an instruction boundary,
// except after a move to or from a segment register, POP sreg, POLL or LOCK (m_no_interrupt: NMI and INT; a prefix
// and its instruction are one step anyway), and after EI (drv_ei_shadow: INT only).  A halted CPU: NMI or an enabled INT is accepted before the instruction after
// the HLT; an INT with IE = 0 releases HALT WITHOUT an acknowledge -- execution resumes after the HLT and the request
// stays pending until interrupts are enabled.  Release and acceptance are separate operations, both here at A.
int nec_common_device::drv_accept()
{
    if (m_pending_irq && !m_no_interrupt) {
        bool nmi = (m_pending_irq & NMI_IRQ) != 0;
        if (nmi || (m_IF && !drv_ei_shadow)) {
            m_icount = 0;
            external_int();
            m_halted = 0;                    // an acceptance ends HALT
            return -m_icount;
        }
    }
    if (m_halted && (m_pending_irq & INT_IRQ))
        m_halted = 0;                        // a masked INT releases HALT: no acknowledge, no clocks (model)
    return 0;
}

int nec_common_device::drv_instruction()
{
    if (m_halted)
        return V40_HALT_SLOT;
    if (drv_fault || !m_MF) {                // BRKEM: the 8080 mode is not modelled
        drv_fault = true;
        return V40_HALT_SLOT;
    }
    m_icount = V40_STEP_ICOUNT;              // one REP iteration per step (the header)
    m_cur_cycles = 0;
    bool cont = m_rep_params != 0;
    if (cont)
        cont_rep();
    else
        (this->*s_nec_instruction[fetchop()])();
    do_prefetch();
    return V40_STEP_ICOUNT - m_icount - (cont ? V40_REP_PREFIX : 0);
}

// ---- cpu.h ------------------------------------------------------------------------------------------------------

struct v40 {
    cpu_bus bus;
    nec_common_device *dev;
    uint64_t cycles, steps;
    uint32_t pc;
};

static uint32_t linear(const nec_common_device &d, uint16_t ip)
{
    return (((uint32_t)d.m_sregs[PS] << 4) + ip) & V40_ADDR_MASK;
}

extern "C" {

v40 *v40_create(const cpu_bus *bus, double clock_hz)
{
    (void)clock_hz;                          // the core counts clocks; the board turns them into time
    v40 *c = new (std::nothrow) v40();
    if (!c)
        return nullptr;
    c->bus = *bus;
    c->dev = new (std::nothrow) nec_common_device(&c->bus);
    if (!c->dev) {
        delete c;
        return nullptr;
    }
    c->dev->init_tables();                   // device_start's tables and first values
    v40_reset(c);
    return c;
}

void v40_destroy(v40 *c)
{
    if (!c)
        return;
    delete c->dev;
    delete c;
}

// Reset (CONTRACT.md 9): MAME's device_reset -- PS = FFFFh, IP = 0, the flags cleared (IE off), the other segments 0,
// no pending REP -- plus what execute_run's state keeps: no shadow, an empty queue, no prefix.  The lines are kept: a
// held INT is asserted again (sampled at the next A); a held NMI stays high with no new edge.
void v40_reset(v40 *c)
{
    nec_common_device &d = *c->dev;
    uint32_t int_held = d.m_irq_state, nmi_held = d.m_nmi_state;
    d.device_reset();
    d.m_no_interrupt = 0;
    d.drv_ei_shadow = 0;
    d.m_prefetch_count = 0;
    d.m_prefetch_reset = 0;
    d.m_seg_prefix = 0;
    d.m_cur_cycles = 0;
    d.drv_fault = false;
    d.drv_undefined = d.drv_undefined_at = 0;
    d.m_nmi_state = nmi_held;
    if (int_held != CLEAR_LINE)
        d.set_int_line(ASSERT_LINE);
    c->cycles = c->steps = 0;
    c->pc = linear(d, d.m_ip);
}

int v40_step(v40 *c)
{
    nec_common_device &d = *c->dev;
    c->pc = linear(d, d.m_ip);               // A's callbacks see the interrupted address
    int acc = d.drv_accept();                // A
    c->cycles += (uint64_t)acc;              // B
    if (d.m_no_interrupt)                    // C
        d.m_no_interrupt--;
    if (d.drv_ei_shadow)                     // C: EI's delay
        d.drv_ei_shadow--;

    c->steps++;                              // D
    if (!d.m_halted)
        d.m_prev_ip = d.m_ip;                // a halted core's step start stays on its HLT
    c->pc = linear(d, d.m_prev_ip);
    if (c->bus.boundary)
        c->bus.boundary(c->bus.ctx, c->pc);

    int ins = d.drv_instruction();           // E
    c->cycles += (uint64_t)ins;              // F
    return acc + ins;
}

uint64_t v40_run(v40 *c, uint64_t budget)
{
    uint64_t done = 0;
    while (done < budget)
        done += (uint64_t)v40_step(c);
    return done;
}

void v40_set_irq(v40 *c, int line, int asserted)
{
    if (line == V40_INT)
        c->dev->execute_set_input(0, asserted ? ASSERT_LINE : CLEAR_LINE);
    else if (line == V40_NMI)
        c->dev->execute_set_input(INPUT_LINE_NMI, asserted ? ASSERT_LINE : CLEAR_LINE);
}

uint64_t v40_cycles(const v40 *c) { return c->cycles; }
uint64_t v40_steps(const v40 *c) { return c->steps; }
uint32_t v40_pc(const v40 *c) { return c->pc; }

void v40_regs_get(const v40 *c, v40_regs *out)
{
    nec_common_device &d = *c->dev;
    out->aw = d.m_regs.w[AW]; out->cw = d.m_regs.w[CW]; out->dw = d.m_regs.w[DW]; out->bw = d.m_regs.w[BW];
    out->sp = d.m_regs.w[SP]; out->bp = d.m_regs.w[BP]; out->ix = d.m_regs.w[IX]; out->iy = d.m_regs.w[IY];
    out->ds1 = d.m_sregs[DS1]; out->ps = d.m_sregs[PS]; out->ss = d.m_sregs[SS]; out->ds0 = d.m_sregs[DS0];
    out->ip = d.m_ip;
    out->psw = d.drv_psw();
    out->halted = d.m_halted ? 1 : 0;
    out->fault = d.drv_fault ? 1 : 0;
    out->undefined = d.drv_undefined;
    out->undefined_at = d.drv_undefined_at;
}

}  // extern "C"
