// license:BSD-3-Clause
// copyright-holders:Juergen Buchmueller
//
// z180_mame_machine.cpp -- GENERATED by extract_z180_machine.py from MAME's src/devices/cpu/z180/z180.cpp
// (the revision in mame_z180/PINNED.txt).  The machine-level parts of MAME's Z180, copied from exact line
// ranges; framework calls replaced as marked 'CHANGED'.  Do not edit: change the script and regenerate.
// The class it compiles against: z180_mame.hpp.  Our step driver and the cpu.h API: z180_mame.cpp.  The
// instruction bodies: mame_z180/ (unchanged).

#include "z180_mame.hpp"

// ---- upstream z180.cpp lines 89-102: interrupt priorities ----------------------------------------
/* interrupt priorities */
#define Z180_INT_TRAP   0           /* Undefined opcode */
#define Z180_INT_NMI    1           /* NMI */
#define Z180_INT_IRQ0   2           /* Execute IRQ1 */
#define Z180_INT_IRQ1   3           /* Execute IRQ1 */
#define Z180_INT_IRQ2   4           /* Execute IRQ2 */
#define Z180_INT_PRT0   5           /* Internal PRT channel 0 */
#define Z180_INT_PRT1   6           /* Internal PRT channel 1 */
#define Z180_INT_DMA0   7           /* Internal DMA channel 0 */
#define Z180_INT_DMA1   8           /* Internal DMA channel 1 */
#define Z180_INT_CSIO   9           /* Internal CSI/O */
#define Z180_INT_ASCI0  10          /* Internal ASCI channel 0 */
#define Z180_INT_ASCI1  11          /* Internal ASCI channel 1 */
#define Z180_INT_MAX    Z180_INT_ASCI1

// ---- upstream z180.cpp lines 169-197: flag bits and the I/O line bits -----------------------------
#define CF  0x01
#define NF  0x02
#define PF  0x04
#define VF  PF
#define XF  0x08
#define HF  0x10
#define YF  0x20
#define ZF  0x40
#define SF  0x80

/* I/O line status flags */
#define Z180_CKA0     0x00000001  /* I/O asynchronous clock 0 (active high) or DREQ0 (mux) */
#define Z180_CKA1     0x00000002  /* I/O asynchronous clock 1 (active high) or TEND1 (mux) */
#define Z180_CKS      0x00000004  /* I/O serial clock (active high) */
#define Z180_CTS0     0x00000100  /* I   clear to send 0 (active low) */
#define Z180_CTS1     0x00000200  /* I   clear to send 1 (active low) or RXS (mux) */
#define Z180_DCD0     0x00000400  /* I   data carrier detect (active low) */
#define Z180_DREQ0    0x00000800  /* I   data request DMA ch 0 (active low) or CKA0 (mux) */
#define Z180_DREQ1    0x00001000  /* I   data request DMA ch 1 (active low) */
#define Z180_RXA0     0x00002000  /* I   asynchronous receive data 0 (active high) */
#define Z180_RXA1     0x00004000  /* I   asynchronous receive data 1 (active high) */
#define Z180_RXS      0x00008000  /* I   clocked serial receive data (active high) or CTS1 (mux) */
#define Z180_RTS0     0x00010000  /*   O request to send (active low) */
#define Z180_TEND0    0x00020000  /*   O transfer end 0 (active low) or CKA1 (mux) */
#define Z180_TEND1    0x00040000  /*   O transfer end 1 (active low) */
#define Z180_A18_TOUT 0x00080000  /*   O transfer out (PRT channel, active low) or A18 (mux) */
#define Z180_TXA0     0x00100000  /*   O asynchronous transmit data 0 (active high) */
#define Z180_TXA1     0x00200000  /*   O asynchronous transmit data 1 (active high) */
#define Z180_TXS      0x00400000  /*   O clocked serial transmit data (active high) */

// ---- upstream z180.cpp lines 199-207: the /TEND outputs -------------------------------------------
bool z180_device::get_tend0()
{
	return !!(m_iol & Z180_TEND0);
}

bool z180_device::get_tend1()
{
	return !!(m_iol & Z180_TEND1);
}

// ---- upstream z180.cpp lines 209-258: the register-name macros ------------------------------------
/*
 * Prevent warnings on NetBSD.  All identifiers beginning with an underscore
 * followed by an uppercase letter are reserved by the C standard (ISO/IEC
 * 9899:1999, 7.1.3) to be used by the implementation.  It'd be best to rename
 * all such instances, but this is less intrusive and error-prone.
 */
#undef _B
#undef _C
#undef _L

#define _PPC    m_PREPC.d /* previous program counter */

#define _PCD    m_PC.d
#define _PC     m_PC.w.l

#define _SPD    m_SP.d
#define _SP     m_SP.w.l

#define _AFD    m_AF.d
#define _AF     m_AF.w.l
#define _A      m_AF.b.h
#define _F      m_AF.b.l

#define _BCD    m_BC.d
#define _BC     m_BC.w.l
#define _B      m_BC.b.h
#define _C      m_BC.b.l

#define _DED    m_DE.d
#define _DE     m_DE.w.l
#define _D      m_DE.b.h
#define _E      m_DE.b.l

#define _HLD    m_HL.d
#define _HL     m_HL.w.l
#define _H      m_HL.b.h
#define _L      m_HL.b.l

#define _IXD    m_IX.d
#define _IX     m_IX.w.l
#define _HX     m_IX.b.h
#define _LX     m_IX.b.l

#define _IYD    m_IY.d
#define _IY     m_IY.w.l
#define _HY     m_IY.b.h
#define _LY     m_IY.b.l


/* 10 TIMER control register (TIF1 and TIF0 are read-only) */

// ---- upstream z180.cpp lines 259-363: the internal registers' bit definitions ---------------------
#define Z180_TCR_TIF1           0x80
#define Z180_TCR_TIF0           0x40
#define Z180_TCR_TIE1           0x20
#define Z180_TCR_TIE0           0x10
#define Z180_TCR_TOC1           0x08
#define Z180_TCR_TOC0           0x04
#define Z180_TCR_TDE1           0x02
#define Z180_TCR_TDE0           0x01

/* 1e (Z8S180/Z8L180) clock multiplier */
#define Z180_CMR_X2             0x80
#define Z180_CMR_LOW_NOISE      0x40

#define Z180_CMR_MASK           0xc0

/* 1f (Z8S180/Z8L180) chip control register */
#define Z180_CCR_CLOCK_DIVIDE   0x80
#define Z180_CCR_STDBY_IDLE1    0x40
#define Z180_CCR_BREXT          0x20
#define Z180_CCR_LNPHI          0x10
#define Z180_CCR_STDBY_IDLE0    0x08
#define Z180_CCR_LNIO           0x04
#define Z180_CCR_LNCPU_CTL      0x02
#define Z180_CCR_LNAD_DATA      0x01

/* 20-22 DMA source address register ch 0 L, H, B */
#define Z180_SAR0_MASK          0x0fffff

/* 23-25 DMA destination address register ch 0 L, H, B */
#define Z180_DAR0_MASK          0x0fffff

/* 28-2a DMA memory address register ch 1 L, H, B */
#define Z180_MAR1_MASK          0x0fffff

/* 2b-2d DMA I/O address register ch 1 L, H, (Z8S180/Z8L180) B */
#define Z180_IAR1_ATF           0x800000
#define Z180_IAR1_ATC           0x400000
#define Z180_IAR1_TOUT_DREQ     0x080000
#define Z180_IAR1_SS            0x070000

#define Z180_IAR1_MASK          0xcfffff

/* 30 DMA status register (DWE1 and DWE0 are write-only, DME is read-only) */
#define Z180_DSTAT_DE1          0x80    /* DMA enable ch 1 */
#define Z180_DSTAT_DE0          0x40    /* DMA enable ch 0 */
#define Z180_DSTAT_DWE1         0x20    /* DMA write enable ch 0 (active low) */
#define Z180_DSTAT_DWE0         0x10    /* DMA write enable ch 1 (active low) */
#define Z180_DSTAT_DIE1         0x08    /* DMA IRQ enable ch 1 */
#define Z180_DSTAT_DIE0         0x04    /* DMA IRQ enable ch 0 */
#define Z180_DSTAT_DME          0x01    /* DMA enable (read only) */

#define Z180_DSTAT_MASK         0xfd

/* 31 DMA mode register */
#define Z180_DMODE_DM           0x30    /* DMA ch 0 destination addressing mode */
#define Z180_DMODE_SM           0x0c    /* DMA ch 0 source addressing mode */
#define Z180_DMODE_MMOD         0x02    /* DMA cycle steal/burst mode select */

#define Z180_DMODE_MASK         0x3e

/* 32 DMA/WAIT control register */
#define Z180_DCNTL_MWI1         0x80
#define Z180_DCNTL_MWI0         0x40
#define Z180_DCNTL_IWI1         0x20
#define Z180_DCNTL_IWI0         0x10
#define Z180_DCNTL_DMS1         0x08
#define Z180_DCNTL_DMS0         0x04
#define Z180_DCNTL_DIM1         0x02
#define Z180_DCNTL_DIM0         0x01

/* 33 INT vector low register */
#define Z180_IL_IL              0xe0

#define Z180_IL_MASK            0xe0

/* 34 INT/TRAP control register (UFO is read-only) */
#define Z180_ITC_TRAP           0x80
#define Z180_ITC_UFO            0x40
#define Z180_ITC_ITE2           0x04
#define Z180_ITC_ITE1           0x02
#define Z180_ITC_ITE0           0x01

#define Z180_ITC_MASK           0xc7

/* 36 refresh control register */
#define Z180_RCR_REFE           0x80
#define Z180_RCR_REFW           0x40
#define Z180_RCR_CYC            0x03

#define Z180_RCR_MASK           0xc3

/* 3a MMU common/bank area register */
#define Z180_CBAR_CA            0xf0
#define Z180_CBAR_BA            0x0f

/* 3e operation mode control register (M1TE is write-onlu) */
#define Z180_OMCR_M1E           0x80
#define Z180_OMCR_M1TE          0x40
#define Z180_OMCR_IOC           0x20

#define Z180_OMCR_MASK          0xe0

/* 3f I/O control register */
#define Z180_IOCR_IOSTP         0x20


// ---- upstream z180.cpp lines 364-377: the CPU prefixes (z180tbl.h depends on this order) ----------
/***************************************************************************
    CPU PREFIXES

    order is important here - see z180tbl.h
***************************************************************************/

#define Z180_PREFIX_op          0
#define Z180_PREFIX_cb          1
#define Z180_PREFIX_dd          2
#define Z180_PREFIX_ed          3
#define Z180_PREFIX_fd          4
#define Z180_PREFIX_xycb        5

#define Z180_PREFIX_COUNT       (Z180_PREFIX_xycb + 1)

// ---- the vendored instruction core (mame_z180/, unchanged) --------------------------------------------
#include "mame_z180/z180ops.h"
#include "mame_z180/z180tbl.h"

#include "mame_z180/z180cb.hxx"
#include "mame_z180/z180xy.hxx"
#include "mame_z180/z180dd.hxx"
#include "mame_z180/z180fd.hxx"
#include "mame_z180/z180ed.hxx"
#include "mame_z180/z180op.hxx"

// ---- upstream z180.cpp lines 422-1096: the internal registers, read and write (Z8S180's extra ones included: the firmware probes CCR) 
uint8_t z180_device::z180_readcontrol(offs_t port)
{
	// normal external readport (ignore the data)
	(void)m_io.read_byte(port);

	// read the internal register
	return z180_internal_port_read(port & (m_extended_io ? 0x7f : 0x3f));
}

uint8_t z180_device::z180_internal_port_read(uint8_t port)
{
	uint8_t data = 0xff;

	switch (port)
	{
	case 0x00:
	case 0x01:
		data = m_asci[port & 1]->cntla_r();
		break;

	case 0x02:
	case 0x03:
		data = m_asci[port & 1]->cntlb_r();
		break;

	case 0x04:
	case 0x05:
		data = m_asci[port & 1]->stat_r();
		break;

	case 0x06:
	case 0x07:
		data = m_asci[port & 1]->tdr_r();
		break;

	case 0x08:
	case 0x09:
		data = m_asci[port & 1]->rdr_r();
		break;

	case 0x0a:
		data = m_csio->cntr_r();
		break;

	case 0x0b:
		data = m_csio->trdr_r();
		break;

	case 0x0c:
		data = m_tmdr_value[0] & 0x00ff;
		LOG("Z180 TMDR0L rd $%02x ($%04x)\n", data, m_tmdr[0].w);
		/* if timer is counting, latch the MSB and set the latch flag */
		if ((m_tcr & Z180_TCR_TDE0) == 0)
		{
			m_tmdr_latch |= 1;
			m_tmdrh[0] = (m_tmdr_value[0] & 0xff00) >> 8;
		}

		if(m_read_tcr_tmdr[0])
		{
			m_tcr &= ~Z180_TCR_TIF0; // reset TIF0
			m_read_tcr_tmdr[0] = 0;
		}
		else
		{
			m_read_tcr_tmdr[0] = 1;
		}
		break;

	case 0x0d:
		/* read latched value? */
		if (m_tmdr_latch & 1)
		{
			m_tmdr_latch &= ~1;
			data = m_tmdrh[0];
		}
		else
		{
			data = (m_tmdr_value[0] & 0xff00) >> 8;
		}

		if(m_read_tcr_tmdr[0])
		{
			m_tcr &= ~Z180_TCR_TIF0; // reset TIF0
			m_read_tcr_tmdr[0] = 0;
		}
		else
		{
			m_read_tcr_tmdr[0] = 1;
		}
		LOG("Z180 TMDR0H rd $%02x ($%04x)\n", data, m_tmdr[0].w);
		break;

	case 0x0e:
		data = m_rldr[0].b.l;
		LOG("Z180 RLDR0L rd $%02x ($%04x)\n", data, m_rldr[0].w);
		break;

	case 0x0f:
		data = m_rldr[0].b.h;
		LOG("Z180 RLDR0H rd $%02x ($%04x)\n", data, m_rldr[0].w);
		break;

	case 0x10:
		data = m_tcr;

		if(m_read_tcr_tmdr[0])
		{
			m_tcr &= ~Z180_TCR_TIF0; // reset TIF0
			m_read_tcr_tmdr[0] = 0;
		}
		else
		{
			m_read_tcr_tmdr[0] = 1;
		}

		if(m_read_tcr_tmdr[1])
		{
			m_tcr &= ~Z180_TCR_TIF1; // reset TIF1
			m_read_tcr_tmdr[1] = 0;
		}
		else
		{
			m_read_tcr_tmdr[1] = 1;
		}

		LOG("Z180 TCR    rd $%02x ($%02x)\n", data, m_tcr);
		break;

	case 0x14:
		data = m_tmdr_value[1];
		LOG("Z180 TMDR1L rd $%02x ($%02x)\n", data, m_tmdr[1].w);
		/* if timer is counting, latch the MSB and set the latch flag */
		if ((m_tcr & Z180_TCR_TDE1) == 0)
		{
			m_tmdr_latch |= 2;
			m_tmdrh[1] = (m_tmdr_value[1] & 0xff00) >> 8;
		}

		if(m_read_tcr_tmdr[1])
		{
			m_tcr &= ~Z180_TCR_TIF1; // reset TIF1
			m_read_tcr_tmdr[1] = 0;
		}
		else
		{
			m_read_tcr_tmdr[1] = 1;
		}
		break;

	case 0x15:
		/* read latched value? */
		if (m_tmdr_latch & 2)
		{
			m_tmdr_latch &= ~2;
			data = m_tmdrh[1];
		}
		else
		{
			data = (m_tmdr_value[1] & 0xff00) >> 8;
		}

		if(m_read_tcr_tmdr[1])
		{
			m_tcr &= ~Z180_TCR_TIF1; // reset TIF1
			m_read_tcr_tmdr[1] = 0;
		}
		else
		{
			m_read_tcr_tmdr[1] = 1;
		}
		LOG("Z180 TMDR1H rd $%02x ($%04x)\n", data, m_tmdr[1].w);
		break;

	case 0x16:
		data = m_rldr[1].b.l;
		LOG("Z180 RLDR1L rd $%02x ($%04x)\n", data, m_rldr[1].w);
		break;

	case 0x17:
		data = m_rldr[1].b.h;
		LOG("Z180 RLDR1H rd $%02x ($%04x)\n", data, m_rldr[1].w);
		break;

	case 0x18:
		data = m_frc;
		LOG("Z180 FRC    rd $%02x\n", data);
		break;

	case 0x19:
		data = 0xff;
		LOG("Z180 IO19   rd $%02x\n", data);
		break;

	case 0x20:
		data = m_dma_sar0.b.l;
		LOG("Z180 SAR0L  rd $%02x ($%05x)\n", data, m_dma_sar0.d);
		break;

	case 0x21:
		data = m_dma_sar0.b.h;
		LOG("Z180 SAR0H  rd $%02x ($%05x)\n", data, m_dma_sar0.d);
		break;

	case 0x22:
		data = m_dma_sar0.b.h2 & (Z180_SAR0_MASK >> 16);
		LOG("Z180 SAR0B  rd $%02x ($%05x)\n", data, m_dma_sar0.d);
		break;

	case 0x23:
		data = m_dma_dar0.b.l;
		LOG("Z180 DAR0L  rd $%02x ($%05x)\n", data, m_dma_dar0.d);
		break;

	case 0x24:
		data = m_dma_dar0.b.h;
		LOG("Z180 DAR0H  rd $%02x ($%05x)\n", data, m_dma_dar0.d);
		break;

	case 0x25:
		data = m_dma_dar0.b.h2 & (Z180_DAR0_MASK >> 16);
		LOG("Z180 DAR0B  rd $%02x ($%05x)\n", data, m_dma_dar0.d);
		break;

	case 0x26:
		data = m_dma_bcr[0].b.l;
		LOG("Z180 BCR0L  rd $%02x ($%04x)\n", data, m_dma_bcr[0].w);
		break;

	case 0x27:
		data = m_dma_bcr[0].b.h;
		LOG("Z180 BCR0H  rd $%02x ($%04x)\n", data, m_dma_bcr[1].w);
		break;

	case 0x28:
		data = m_dma_mar1.b.l;
		LOG("Z180 MAR1L  rd $%02x ($%05x)\n", data, m_dma_mar1.d);
		break;

	case 0x29:
		data = m_dma_mar1.b.h;
		LOG("Z180 MAR1H  rd $%02x ($%05x)\n", data, m_dma_mar1.d);
		break;

	case 0x2a:
		data = m_dma_mar1.b.h2 & (Z180_MAR1_MASK >> 16);
		LOG("Z180 MAR1B  rd $%02x ($%05x)\n", data, m_dma_mar1.d);
		break;

	case 0x2b:
		data = m_dma_iar1.b.l;
		LOG("Z180 IAR1L  rd $%02x ($%05x)\n", data, m_dma_iar1.d);
		break;

	case 0x2c:
		data = m_dma_iar1.b.h;
		LOG("Z180 IAR1H  rd $%02x ($%05x)\n", data, m_dma_iar1.d);
		break;

	case 0x2d:
		data = m_dma_iar1.b.h2 & (Z180_IAR1_MASK >> 16);
		LOG("Z180 IAR1B  rd $%02x ($%05x)\n", data, m_dma_iar1.d);
		break;

	case 0x2e:
		data = m_dma_bcr[1].b.l;
		LOG("Z180 BCR1L  rd $%02x ($%04x)\n", data, m_dma_bcr[1].w);
		break;

	case 0x2f:
		data = m_dma_bcr[1].b.h;
		LOG("Z180 BCR1H  rd $%02x ($%04x)\n", data, m_dma_bcr[1].w);
		break;

	case 0x30:
		data = m_dstat | ~Z180_DSTAT_MASK;
		LOG("Z180 DSTAT  rd $%02x ($%02x)\n", data, m_dstat);
		break;

	case 0x31:
		data = m_dmode | ~Z180_DMODE_MASK;
		LOG("Z180 DMODE  rd $%02x ($%02x)\n", data, m_dmode);
		break;

	case 0x32:
		data = m_dcntl;
		LOG("Z180 DCNTL  rd $%02x\n", data);
		break;

	case 0x33:
		data = m_il & Z180_IL_MASK;
		LOG("Z180 IL     rd $%02x ($%02x)\n", data, m_il);
		break;

	case 0x34:
		data = m_itc | ~Z180_ITC_MASK;
		LOG("Z180 ITC    rd $%02x ($%02x)\n", data, m_itc);
		break;

	case 0x36:
		data = m_rcr | ~Z180_RCR_MASK;
		LOG("Z180 RCR    rd $%02x ($%02x)\n", data, m_rcr);
		break;

	case 0x38:
		data = m_mmu_cbr;
		LOG("Z180 CBR    rd $%02x\n", data);
		break;

	case 0x39:
		data = m_mmu_bbr;
		LOG("Z180 BBR    rd $%02x\n", data);
		break;

	case 0x3a:
		data = m_mmu_cbar;
		LOG("Z180 CBAR   rd $%02x\n", data);
		break;

	case 0x3e:
		data = m_omcr | Z180_OMCR_M1TE | ~Z180_OMCR_MASK;
		LOG("Z180 OMCR   rd $%02x ($%02x)\n", data, m_omcr);
		break;

	case 0x3f:
		data = m_iocr | ~(m_extended_io ? 0xa0 : 0xe0);
		LOG("Z180 IOCR   rd $%02x ($%02x)\n", data, m_iocr);
		break;

	default:
		data = 0xff;
		LOG("Z180 IO%02X   rd $%02x\n", port, data);
		break;
	}

	return data;
}

void z180_device::z180_writecontrol(offs_t port, uint8_t data)
{
	// normal external write port
	m_io.write_byte(port, data);

	// store the data in the internal register
	z180_internal_port_write(port & (m_extended_io ? 0x7f : 0x3f), data);
}

void z180_device::z180_internal_port_write(uint8_t port, uint8_t data)
{
	switch (port)
	{
	case 0x00:
	case 0x01:
		m_asci[port & 1]->cntla_w(data);
		break;

	case 0x02:
	case 0x03:
		m_asci[port & 1]->cntlb_w(data);
		break;

	case 0x04:
	case 0x05:
		m_asci[port & 1]->stat_w(data);
		break;

	case 0x06:
	case 0x07:
		m_asci[port & 1]->tdr_w(data);
		break;

	case 0x08:
	case 0x09:
		m_asci[port & 1]->rdr_w(data);
		break;

	case 0x0a:
		m_csio->cntr_w(data);
		break;

	case 0x0b:
		m_csio->trdr_w(data);
		break;

	case 0x0c:
		LOG("Z180 TMDR0L wr $%02x\n", data);
		m_tmdr[0].b.l = data;
		m_tmdr_value[0] = (m_tmdr_value[0] & 0xff00) | m_tmdr[0].b.l;
		break;

	case 0x0d:
		LOG("Z180 TMDR0H wr $%02x\n", data);
		m_tmdr[0].b.h = data;
		m_tmdr_value[0] = (m_tmdr_value[0] & 0x00ff) | (m_tmdr[0].b.h << 8);
		break;

	case 0x0e:
		LOG("Z180 RLDR0L wr $%02x\n", data);
		m_rldr[0].b.l = data;
		break;

	case 0x0f:
		LOG("Z180 RLDR0H wr $%02x\n", data);
		m_rldr[0].b.h = data;
		break;

	case 0x10:
		LOG("Z180 TCR    wr $%02x ($%02x)\n", data,  data & ~(Z180_TCR_TIF1 | Z180_TCR_TIF0));
		{
			uint16_t old = m_tcr;
			/* Force reload on state change */
			m_tcr = (m_tcr & (Z180_TCR_TIF1 | Z180_TCR_TIF0)) | (data & ~(Z180_TCR_TIF1 | Z180_TCR_TIF0));
			if (!(old & Z180_TCR_TDE0) && (m_tcr & Z180_TCR_TDE0))
				m_tmdr_value[0] = m_rldr[0].w;
			if (!(old & Z180_TCR_TDE1) && (m_tcr & Z180_TCR_TDE1))
				m_tmdr_value[1] = m_rldr[1].w;
		}

		break;

	case 0x14:
		LOG("Z180 TMDR1L wr $%02x\n", data);
		m_tmdr[1].b.l = data;
		m_tmdr_value[1] = (m_tmdr_value[1] & 0xff00) | m_tmdr[1].b.l;
		break;

	case 0x15:
		LOG("Z180 TMDR1H wr $%02x\n", data);
		m_tmdr[1].b.h = data;
		m_tmdr_value[1] = (m_tmdr_value[1] & 0x00ff) | (m_tmdr[1].b.h << 8);
		break;

	case 0x16:
		LOG("Z180 RLDR1L wr $%02x\n", data);
		m_rldr[1].b.l = data;
		break;

	case 0x17:
		LOG("Z180 RLDR1H wr $%02x\n", data);
		m_rldr[1].b.h = data;
		break;

	case 0x18:
		LOG("Z180 FRC    wr $%02x\n", data);
		// FRC is read-only
		break;

	case 0x20:
		LOG("Z180 SAR0L  wr $%02x\n", data);
		m_dma_sar0.b.l = data;
		break;

	case 0x21:
		LOG("Z180 SAR0H  wr $%02x\n", data);
		m_dma_sar0.b.h = data;
		break;

	case 0x22:
		LOG("Z180 SAR0B  wr $%02x ($%02x)\n", data,  data & (Z180_SAR0_MASK >> 16));
		m_dma_sar0.b.h2 = data & (Z180_SAR0_MASK >> 16);
		break;

	case 0x23:
		LOG("Z180 DAR0L  wr $%02x\n", data);
		m_dma_dar0.b.l = data;
		break;

	case 0x24:
		LOG("Z180 DAR0H  wr $%02x\n", data);
		m_dma_dar0.b.h = data;
		break;

	case 0x25:
		LOG("Z180 DAR0B  wr $%02x ($%02x)\n", data,  data & (Z180_DAR0_MASK >> 16));
		m_dma_dar0.b.h2 = data & (Z180_DAR0_MASK >> 16);
		break;

	case 0x26:
		LOG("Z180 BCR0L  wr $%02x\n", data);
		m_dma_bcr[0].b.l = data;
		break;

	case 0x27:
		LOG("Z180 BCR0H  wr $%02x\n", data);
		m_dma_bcr[0].b.h = data;
		break;

	case 0x28:
		LOG("Z180 MAR1L  wr $%02x\n", data);
		m_dma_mar1.b.l = data;
		break;

	case 0x29:
		LOG("Z180 MAR1H  wr $%02x\n", data);
		m_dma_mar1.b.h = data;
		break;

	case 0x2a:
		LOG("Z180 MAR1B  wr $%02x ($%02x)\n", data,  data & (Z180_MAR1_MASK >> 16));
		m_dma_mar1.b.h2 = data & (Z180_MAR1_MASK >> 16);
		break;

	case 0x2b:
		LOG("Z180 IAR1L  wr $%02x\n", data);
		m_dma_iar1.b.l = data;
		break;

	case 0x2c:
		LOG("Z180 IAR1H  wr $%02x\n", data);
		m_dma_iar1.b.h = data;
		break;

	case 0x2d:
		LOG("Z180 IAR1B  wr $%02x ($%02x)\n", data,  data & (Z180_IAR1_MASK >> 16));
		m_dma_iar1.b.h2 = data & (Z180_IAR1_MASK >> 16);
		break;

	case 0x2e:
		LOG("Z180 BCR1L  wr $%02x\n", data);
		m_dma_bcr[1].b.l = data;
		break;

	case 0x2f:
		LOG("Z180 BCR1H  wr $%02x\n", data);
		m_dma_bcr[1].b.h = data;
		break;

	case 0x30:
		LOG("Z180 DSTAT  wr $%02x ($%02x)\n", data,  data & Z180_DSTAT_MASK & ~Z180_DSTAT_DME);
		m_dstat = (m_dstat & Z180_DSTAT_DME) | (data & Z180_DSTAT_MASK & ~Z180_DSTAT_DME);
		if ((data & (Z180_DSTAT_DE1 | Z180_DSTAT_DWE1)) == Z180_DSTAT_DE1)
		{
			m_dstat |= Z180_DSTAT_DME;  /* DMA enable */
		}
		if ((data & (Z180_DSTAT_DE0 | Z180_DSTAT_DWE0)) == Z180_DSTAT_DE0)
		{
			m_dstat |= Z180_DSTAT_DME;  /* DMA enable */
		}
		break;

	case 0x31:
		LOG("Z180 DMODE  wr $%02x ($%02x)\n", data,  data & Z180_DMODE_MASK);
		m_dmode = data & Z180_DMODE_MASK;
		break;

	case 0x32:
		LOG("Z180 DCNTL  wr $%02x\n", data);
		m_dcntl = data;
		break;

	case 0x33:
		LOG("Z180 IL     wr $%02x ($%02x)\n", data,  data & Z180_IL_MASK);
		m_il = data & Z180_IL_MASK;
		break;

	case 0x34:
		LOG("Z180 ITC    wr $%02x ($%02x)\n", data,  data & Z180_ITC_MASK & ~Z180_ITC_UFO);
		// CHANGED: software can clear ITC.TRAP but never set it (Zilog UM, ITC); UFO stays read-only
		m_itc = (m_itc & Z180_ITC_UFO) | (m_itc & data & Z180_ITC_TRAP)
		        | (data & Z180_ITC_MASK & ~(Z180_ITC_UFO | Z180_ITC_TRAP));
		break;

	case 0x36:
		LOG("Z180 RCR    wr $%02x ($%02x)\n", data,  data & Z180_RCR_MASK);
		m_rcr = data & Z180_RCR_MASK;
		break;

	case 0x38:
		LOG("Z180 CBR    wr $%02x\n", data);
		m_mmu_cbr = data;
		z180_mmu();
		break;

	case 0x39:
		LOG("Z180 BBR    wr $%02x\n", data);
		m_mmu_bbr = data;
		z180_mmu();
		break;

	case 0x3a:
		LOG("Z180 CBAR   wr $%02x\n", data);
		m_mmu_cbar = data;
		z180_mmu();
		break;

	case 0x3e:
		LOG("Z180 OMCR   wr $%02x ($%02x)\n", data,  data & Z180_OMCR_MASK);
		m_omcr = data & Z180_OMCR_MASK;
		break;

	case 0x3f:
		LOG("Z180 IOCR   wr $%02x ($%02x)\n", data,  data & (m_extended_io ? 0xa0 : 0xe0));
		m_iocr = data & (m_extended_io ? 0xa0 : 0xe0);
		break;

	default:
		LOG("Z180 IO%02X   wr $%02x\n", port, data);
		break;

	}
}

uint8_t z8s180_device::z180_internal_port_read(uint8_t port)
{
	uint8_t data = 0xff;

	switch (port)
	{
	case 0x12:
	case 0x13:
		data = m_asci[port & 1]->asext_r();
		break;

	case 0x1a:
	case 0x1b:
		data = m_asci[port & 1]->astcl_r();
		break;

	case 0x1c:
	case 0x1d:
		data = m_asci[port & 1]->astcl_r();
		break;

	case 0x1e:
		data = m_cmr | ~Z180_CMR_MASK;
		LOG("Z180 CMR    rd $%02x ($%02x)\n", data, m_cmr);
		break;

	case 0x1f:
		data = m_ccr;
		LOG("Z180 CCR    rd $%02x\n", data);
		break;

	default:
		data = z180_device::z180_internal_port_read(port);
		break;
	}

	return data;
}

void z8s180_device::z180_internal_port_write(uint8_t port, uint8_t data)
{
	switch (port)
	{
	case 0x12:
	case 0x13:
		m_asci[port & 1]->asext_w(data);
		break;

	case 0x1a:
	case 0x1b:
		m_asci[port & 1]->astcl_w(data);
		break;

	case 0x1c:
	case 0x1d:
		m_asci[port & 1]->astch_w(data);
		break;

	case 0x1e:
		LOG("Z180 CMR    wr $%02x ($%02x)\n", data,  data & Z180_CMR_MASK);
		m_cmr = data & Z180_CMR_MASK;
		notify_clock_changed();
		break;

	case 0x1f:
		LOG("Z180 CCR    wr $%02x\n", data);
		m_ccr = data;
		notify_clock_changed();
		break;

	default:
		z180_device::z180_internal_port_write(port, data);
		break;
	}
}

// ---- upstream z180.cpp lines 1098-1333: the two DMA channels ----------------------------------------
int z180_device::z180_dma0(int max_cycles)
{
	offs_t sar0 = m_dma_sar0.d;
	offs_t dar0 = m_dma_dar0.d;
	int bcr0 = m_dma_bcr[0].w;

	if (bcr0 == 0)
	{
		bcr0 = 0x10000;
	}

	int count = (m_dmode & Z180_DMODE_MMOD) ? bcr0 : 1;
	int cycles = 0;

	if (!(m_dstat & Z180_DSTAT_DE0))
	{
		return 0;
	}

	while (count > 0)
	{
		m_extra_cycles = 0;
		/* last transfer happening now? */
		if (bcr0 == 1)
		{
			m_iol |= Z180_TEND0;
			m_tend0_cb(ASSERT_LINE);
		}
		switch( m_dmode & (Z180_DMODE_SM | Z180_DMODE_DM) )
		{
		case 0x00:  /* memory SAR0+1 to memory DAR0+1 */
			z180_write_memory(dar0++, z180_read_memory(sar0++));
			cycles += memory_wait_states() * 2;
			bcr0--;
			break;
		case 0x04:  /* memory SAR0-1 to memory DAR0+1 */
			z180_write_memory(dar0++, z180_read_memory(sar0--));
			cycles += memory_wait_states() * 2;
			bcr0--;
			break;
		case 0x08:  /* memory SAR0 fixed to memory DAR0+1 */
			z180_write_memory(dar0++, z180_read_memory(sar0));
			cycles += memory_wait_states() * 2;
			bcr0--;
			break;
		case 0x0c:  /* I/O SAR0 fixed to memory DAR0+1 */
			if (m_iol & Z180_DREQ0)
			{
				z180_write_memory(dar0++, IN(sar0));
				cycles += memory_wait_states();
				bcr0--;
				/* edge sensitive DREQ0 ? */
				if (m_dcntl & Z180_DCNTL_DMS0)
				{
					m_iol &= ~Z180_DREQ0;
					count = 0;
				}
			}
			break;
		case 0x10:  /* memory SAR0+1 to memory DAR0-1 */
			z180_write_memory(dar0--, z180_read_memory(sar0++));
			cycles += memory_wait_states() * 2;
			bcr0--;
			break;
		case 0x14:  /* memory SAR0-1 to memory DAR0-1 */
			z180_write_memory(dar0--, z180_read_memory(sar0--));
			cycles += memory_wait_states() * 2;
			bcr0--;
			break;
		case 0x18:  /* memory SAR0 fixed to memory DAR0-1 */
			z180_write_memory(dar0--, z180_read_memory(sar0));
			cycles += memory_wait_states() * 2;
			bcr0--;
			break;
		case 0x1c:  /* I/O SAR0 fixed to memory DAR0-1 */
			if (m_iol & Z180_DREQ0)
			{
				z180_write_memory(dar0--, IN(sar0));
				cycles += memory_wait_states();
				bcr0--;
				/* edge sensitive DREQ0 ? */
				if (m_dcntl & Z180_DCNTL_DMS0)
				{
					m_iol &= ~Z180_DREQ0;
					count = 0;
				}
			}
			break;
		case 0x20:  /* memory SAR0+1 to memory DAR0 fixed */
			z180_write_memory(dar0, z180_read_memory(sar0++));
			cycles += memory_wait_states() * 2;
			bcr0--;
			break;
		case 0x24:  /* memory SAR0-1 to memory DAR0 fixed */
			z180_write_memory(dar0, z180_read_memory(sar0--));
			cycles += memory_wait_states() * 2;
			bcr0--;
			break;
		case 0x28:  /* reserved */
			break;
		case 0x2c:  /* reserved */
			break;
		case 0x30:  /* memory SAR0+1 to I/O DAR0 fixed */
			if (m_iol & Z180_DREQ0)
			{
				OUT(dar0, z180_read_memory(sar0++));
				cycles += memory_wait_states();
				bcr0--;
				/* edge sensitive DREQ0 ? */
				if (m_dcntl & Z180_DCNTL_DMS0)
				{
					m_iol &= ~Z180_DREQ0;
					count = 0;
				}
			}
			break;
		case 0x34:  /* memory SAR0-1 to I/O DAR0 fixed */
			if (m_iol & Z180_DREQ0)
			{
				OUT(dar0, z180_read_memory(sar0--));
				cycles += memory_wait_states();
				bcr0--;
				/* edge sensitive DREQ0 ? */
				if (m_dcntl & Z180_DCNTL_DMS0)
				{
					m_iol &= ~Z180_DREQ0;
					count = 0;
				}
			}
			break;
		case 0x38:  /* reserved */
			break;
		case 0x3c:  /* reserved */
			break;
		}
		count--;
		cycles += 6 + m_extra_cycles; // use extra_cycles for I/O wait states
		if (cycles > max_cycles)
			break;
	}

	m_dma_sar0.d = sar0;
	m_dma_dar0.d = dar0;
	m_dma_bcr[0].w = bcr0;

	/* DMA terminal count? */
	if (bcr0 == 0)
	{
		m_iol &= ~Z180_TEND0;
		m_tend0_cb(CLEAR_LINE);
		m_dstat &= ~Z180_DSTAT_DE0;
		/* terminal count interrupt enabled? */
		if (m_dstat & Z180_DSTAT_DIE0)
		{
			m_int_pending[Z180_INT_DMA0] = 1;
		}
	}
	return cycles;
}

int z180_device::z180_dma1()
{
	offs_t mar1 = m_dma_mar1.d;
	offs_t iar1 = m_dma_iar1.w.l;
	int bcr1 = m_dma_bcr[1].w;

	if (bcr1 == 0)
	{
		bcr1 = 0x10000;
	}

	int cycles = 0;

	if ((m_iol & Z180_DREQ1) == 0)
		return 0;

	if (!(m_dstat & Z180_DSTAT_DE1))
	{
		return 0;
	}

	/* last transfer happening now? */
	if (bcr1 == 1)
	{
		m_iol |= Z180_TEND1;
		m_tend1_cb(ASSERT_LINE);
	}

	m_extra_cycles = 0;

	switch (m_dcntl & (Z180_DCNTL_DIM1 | Z180_DCNTL_DIM0))
	{
	case 0x00:  /* memory MAR1+1 to I/O IAR1 fixed */
		m_io.write_byte(iar1, z180_read_memory(mar1++));
		bcr1--;
		break;
	case 0x01:  /* memory MAR1-1 to I/O IAR1 fixed */
		m_io.write_byte(iar1, z180_read_memory(mar1--));
		bcr1--;
		break;
	case 0x02:  /* I/O IAR1 fixed to memory MAR1+1 */
		z180_write_memory(mar1++, m_io.read_byte(iar1));
		bcr1--;
		break;
	case 0x03:  /* I/O IAR1 fixed to memory MAR1-1 */
		z180_write_memory(mar1--, m_io.read_byte(iar1));
		bcr1--;
		break;
	}

	cycles += memory_wait_states();
	cycles += m_extra_cycles; // use extra_cycles for I/O wait states

	/* edge sensitive DREQ1 ? */
	if (m_dcntl & Z180_DCNTL_DMS1)
	{
		m_iol &= ~Z180_DREQ1;
	}

	m_dma_mar1.d = mar1;
	m_dma_bcr[1].w = bcr1;

	/* DMA terminal count? */
	if (bcr1 == 0)
	{
		m_iol &= ~Z180_TEND1;
		m_tend1_cb(CLEAR_LINE);
		m_dstat &= ~Z180_DSTAT_DE1;
		if (m_dstat & Z180_DSTAT_DIE1)
			m_int_pending[Z180_INT_DMA1] = 1;
	}

	/* six cycles per transfer (minimum) */
	return 6 + cycles;
}


// ---- upstream z180.cpp lines 1334-1457: the I/O lines -----------------------------------------------
void z180_device::z180_write_iolines(uint32_t data)
{
	uint32_t changes = m_iol ^ data;

	/* I/O asynchronous clock 0 (active high) or DREQ0 (mux) */
	if (changes & Z180_CKA0)
	{
		LOG("Z180 CKA0   %d\n", data & Z180_CKA0 ? 1 : 0);
		m_iol = (m_iol & ~Z180_CKA0) | (data & Z180_CKA0);
	}

	/* I/O asynchronous clock 1 (active high) or TEND1 (mux) */
	if (changes & Z180_CKA1)
	{
		LOG("Z180 CKA1   %d\n", data & Z180_CKA1 ? 1 : 0);
		m_iol = (m_iol & ~Z180_CKA1) | (data & Z180_CKA1);
	}

	/* I/O serial clock (active high) */
	if (changes & Z180_CKS)
	{
		LOG("Z180 CKS    %d\n", data & Z180_CKS ? 1 : 0);
		m_iol = (m_iol & ~Z180_CKS) | (data & Z180_CKS);
	}

	/* I   clear to send 0 (active low) */
	if (changes & Z180_CTS0)
	{
		LOG("Z180 CTS0   %d\n", data & Z180_CTS0 ? 1 : 0);
		m_iol = (m_iol & ~Z180_CTS0) | (data & Z180_CTS0);
	}

	/* I   clear to send 1 (active low) or RXS (mux) */
	if (changes & Z180_CTS1)
	{
		LOG("Z180 CTS1   %d\n", data & Z180_CTS1 ? 1 : 0);
		m_iol = (m_iol & ~Z180_CTS1) | (data & Z180_CTS1);
	}

	/* I   data carrier detect (active low) */
	if (changes & Z180_DCD0)
	{
		LOG("Z180 DCD0   %d\n", data & Z180_DCD0 ? 1 : 0);
		m_iol = (m_iol & ~Z180_DCD0) | (data & Z180_DCD0);
	}

	/* I   data request DMA ch 0 (active low) or CKA0 (mux) */
	if (changes & Z180_DREQ0)
	{
		LOG("Z180 DREQ0  %d\n", data & Z180_DREQ0 ? 1 : 0);
		m_iol = (m_iol & ~Z180_DREQ0) | (data & Z180_DREQ0);
	}

	/* I   data request DMA ch 1 (active low) */
	if (changes & Z180_DREQ1)
	{
		LOG("Z180 DREQ1  %d\n", data & Z180_DREQ1 ? 1 : 0);
		m_iol = (m_iol & ~Z180_DREQ1) | (data & Z180_DREQ1);
	}

	/* I   asynchronous receive data 0 (active high) */
	if (changes & Z180_RXA0)
	{
		LOG("Z180 RXA0   %d\n", data & Z180_RXA0 ? 1 : 0);
		m_iol = (m_iol & ~Z180_RXA0) | (data & Z180_RXA0);
	}

	/* I   asynchronous receive data 1 (active high) */
	if (changes & Z180_RXA1)
	{
		LOG("Z180 RXA1   %d\n", data & Z180_RXA1 ? 1 : 0);
		m_iol = (m_iol & ~Z180_RXA1) | (data & Z180_RXA1);
	}

	/* I   clocked serial receive data (active high) or CTS1 (mux) */
	if (changes & Z180_RXS)
	{
		LOG("Z180 RXS    %d\n", data & Z180_RXS ? 1 : 0);
		m_iol = (m_iol & ~Z180_RXS) | (data & Z180_RXS);
	}

	/*   O request to send (active low) */
	if (changes & Z180_RTS0)
	{
		LOG("Z180 RTS0   won't change output\n");
	}

	/*   O transfer end 0 (active low) or CKA1 (mux) */
	if (changes & Z180_TEND0)
	{
		LOG("Z180 TEND0  won't change output\n");
	}

	/*   O transfer end 1 (active low) */
	if (changes & Z180_TEND1)
	{
		LOG("Z180 TEND1  won't change output\n");
	}

	/*   O transfer out (PRT channel, active low) or A18 (mux) */
	if (changes & Z180_A18_TOUT)
	{
		LOG("Z180 TOUT   won't change output\n");
	}

	/*   O asynchronous transmit data 0 (active high) */
	if (changes & Z180_TXA0)
	{
		LOG("Z180 TXA0   won't change output\n");
	}

	/*   O asynchronous transmit data 1 (active high) */
	if (changes & Z180_TXA1)
	{
		LOG("Z180 TXA1   won't change output\n");
	}

	/*   O clocked serial transmit data (active high) */
	if (changes & Z180_TXS)
	{
		LOG("Z180 TXS    won't change output\n");
	}
}


// ---- upstream z180.cpp lines 1458-1536: the flag tables (device_start's table part) -----------------
void z180_device::init_tables()   // CHANGED: was device_start(); only its flag-table part is kept
{
	int i, p;
	int oldval, newval, val;
	uint8_t *padd, *padc, *psub, *psbc;

	/* allocate big flag arrays once */
	SZHVC_add = std::make_unique<uint8_t[]>(2*256*256);
	SZHVC_sub = std::make_unique<uint8_t[]>(2*256*256);

	padd = &SZHVC_add[  0*256];
	padc = &SZHVC_add[256*256];
	psub = &SZHVC_sub[  0*256];
	psbc = &SZHVC_sub[256*256];
	for (oldval = 0; oldval < 256; oldval++)
	{
		for (newval = 0; newval < 256; newval++)
		{
			/* add or adc w/o carry set */
			val = newval - oldval;
			*padd = (newval) ? ((newval & 0x80) ? SF : 0) : ZF;
			*padd |= (newval & (YF | XF));  /* undocumented flag bits 5+3 */

			if( (newval & 0x0f) < (oldval & 0x0f) ) *padd |= HF;
			if( newval < oldval ) *padd |= CF;
			if( (val^oldval^0x80) & (val^newval) & 0x80 ) *padd |= VF;
			padd++;

			/* adc with carry set */
			val = newval - oldval - 1;
			*padc = (newval) ? ((newval & 0x80) ? SF : 0) : ZF;
			*padc |= (newval & (YF | XF));  /* undocumented flag bits 5+3 */
			if( (newval & 0x0f) <= (oldval & 0x0f) ) *padc |= HF;
			if( newval <= oldval ) *padc |= CF;
			if( (val^oldval^0x80) & (val^newval) & 0x80 ) *padc |= VF;
			padc++;

			/* cp, sub or sbc w/o carry set */
			val = oldval - newval;
			*psub = NF | ((newval) ? ((newval & 0x80) ? SF : 0) : ZF);
			*psub |= (newval & (YF | XF));  /* undocumented flag bits 5+3 */
			if( (newval & 0x0f) > (oldval & 0x0f) ) *psub |= HF;
			if( newval > oldval ) *psub |= CF;
			if( (val^oldval) & (oldval^newval) & 0x80 ) *psub |= VF;
			psub++;

			/* sbc with carry set */
			val = oldval - newval - 1;
			*psbc = NF | ((newval) ? ((newval & 0x80) ? SF : 0) : ZF);
			*psbc |= (newval & (YF | XF));  /* undocumented flag bits 5+3 */
			if( (newval & 0x0f) >= (oldval & 0x0f) ) *psbc |= HF;
			if( newval >= oldval ) *psbc |= CF;
			if( (val^oldval) & (oldval^newval) & 0x80 ) *psbc |= VF;
			psbc++;
		}
	}
	for (i = 0; i < 256; i++)
	{
		p = 0;
		if( i&0x01 ) ++p;
		if( i&0x02 ) ++p;
		if( i&0x04 ) ++p;
		if( i&0x08 ) ++p;
		if( i&0x10 ) ++p;
		if( i&0x20 ) ++p;
		if( i&0x40 ) ++p;
		if( i&0x80 ) ++p;
		SZ[i] = i ? i & SF : ZF;
		SZ[i] |= (i & (YF | XF));       /* undocumented flag bits 5+3 */
		SZ_BIT[i] = i ? i & SF : ZF | PF;
		SZ_BIT[i] |= (i & (YF | XF));   /* undocumented flag bits 5+3 */
		SZP[i] = SZ[i] | ((p & 1) ? 0 : PF);
		SZHV_inc[i] = SZ[i];
		if( i == 0x80 ) SZHV_inc[i] |= VF;
		if( (i & 0x0f) == 0x00 ) SZHV_inc[i] |= HF;
		SZHV_dec[i] = SZ[i] | NF;
		if( i == 0x7f ) SZHV_dec[i] |= VF;
		if( (i & 0x0f) == 0x0f ) SZHV_dec[i] |= HF;
	}
}   // CHANGED: closes init_tables(); upstream's device_start goes on with framework set-up

// ---- upstream z180.cpp lines 1681-1751: reset -------------------------------------------------------
/****************************************************************************
 * Reset registers to their initial values
 ****************************************************************************/
void z180_device::device_reset()
{
	_PPC = 0;
	_PCD = 0;
	_SPD = 0;
	_AFD = 0;
	_BCD = 0;
	_DED = 0;
	_HLD = 0;
	_IXD = 0;
	_IYD = 0;
	m_AF2.d = 0;
	m_BC2.d = 0;
	m_DE2.d = 0;
	m_HL2.d = 0;
	m_R = 0;
	m_R2 = 0;
	m_IFF1 = 0;
	m_IFF2 = 0;
	m_HALT = 0;
	m_IM = 0;
	m_I = 0;
	m_tmdr_latch = 0;
	m_read_tcr_tmdr[0] = 0;
	m_read_tcr_tmdr[1] = 0;
	m_iol = 0;
	memset(m_mmu, 0, sizeof(m_mmu));
	m_tmdrh[0] = 0;
	m_tmdrh[1] = 0;
	m_tmdr_value[0] = 0xffff;
	m_tmdr_value[1] = 0xffff;
	m_nmi_state = CLEAR_LINE;
	m_nmi_pending = 0;
	m_irq_state[0] = CLEAR_LINE;
	m_irq_state[1] = CLEAR_LINE;
	m_irq_state[2] = CLEAR_LINE;
	m_after_EI = 0;
	m_ea = 0;

	memcpy(m_cc, (uint8_t *)cc_default, sizeof(m_cc));
	_IX = _IY = 0xffff; /* IX and IY are FFFF after a reset! */
	_F = ZF;          /* Zero flag is set */

	for (int i=0; i <= Z180_INT_MAX; i++)
	{
		m_int_pending[i] = 0;
	}

	m_frc = 0xff;
	m_frc_prescale = 0;

	/* reset io registers */
	m_tcr = 0x00;
	m_dma_iar1.b.h2 = 0x00;
	m_dstat = Z180_DSTAT_DWE1 | Z180_DSTAT_DWE0;
	m_dmode = 0x00;
	m_dcntl = 0xf0; // maximum number of memory and I/O wait states
	m_il = 0x00;
	m_itc = Z180_ITC_ITE0;
	m_rcr = Z180_RCR_REFE | Z180_RCR_REFW;
	m_mmu_cbr = 0x00;
	m_mmu_bbr = 0x00;
	m_mmu_cbar = 0xf0;
	m_omcr = Z180_OMCR_M1E | Z180_OMCR_M1TE | Z180_OMCR_IOC;
	m_iocr = 0x00;

	z180_mmu();
}

// ---- upstream z180.cpp lines 1771-1778: the Z8S180's reset ------------------------------------------
void z8s180_device::device_reset()
{
	z180_device::device_reset();

	m_cmr = 0x00;
	m_ccr = 0x00;
	notify_clock_changed();
}

// ---- upstream z180.cpp lines 1789-1887: the timers, the interrupt check, the timer clocking ---------
void z180_device::clock_timers()
{
	/* Programmable Reload Timer 0 */
	if(m_tcr & Z180_TCR_TDE0)
	{
		if(m_tmdr_value[0] == 0)
		{
			m_tmdr_value[0] = m_rldr[0].w;
			m_tcr |= Z180_TCR_TIF0;
		}
		else
			m_tmdr_value[0]--;
	}

	/* Programmable Reload Timer 1 */
	if(m_tcr & Z180_TCR_TDE1)
	{
		if(m_tmdr_value[1] == 0)
		{
			m_tmdr_value[1] = m_rldr[1].w;
			m_tcr |= Z180_TCR_TIF1;
		}
		else
			m_tmdr_value[1]--;
	}

	if((m_tcr & Z180_TCR_TIE0) && (m_tcr & Z180_TCR_TIF0))
	{
		// check if we can take the interrupt
		if(m_IFF1 && !m_after_EI)
			m_int_pending[Z180_INT_PRT0] = 1;
	}

	if((m_tcr & Z180_TCR_TIE1) && (m_tcr & Z180_TCR_TIF1))
	{
		// check if we can take the interrupt
		if(m_IFF1 && !m_after_EI)
			m_int_pending[Z180_INT_PRT1] = 1;
	}
}

int z180_device::check_interrupts()
{
	/* check for IRQs before each instruction */
	if (m_IFF1 && !m_after_EI)
	{
		if (m_irq_state[0] != CLEAR_LINE && (m_itc & Z180_ITC_ITE0) == Z180_ITC_ITE0)
			m_int_pending[Z180_INT_IRQ0] = 1;

		if (m_irq_state[1] != CLEAR_LINE && (m_itc & Z180_ITC_ITE1) == Z180_ITC_ITE1)
			m_int_pending[Z180_INT_IRQ1] = 1;

		if (m_irq_state[2] != CLEAR_LINE && (m_itc & Z180_ITC_ITE2) == Z180_ITC_ITE2)
			m_int_pending[Z180_INT_IRQ2] = 1;

		// CHANGED: the PRT requests are levels of TIF and TIE, taken here before the priority choice as the
		// ASCI's and CSIO's are (clock_timers cached them only if a timer clock fell while IFF1 was set and no EI
		// shadow was on, so a lower source such as DMA0 could win over a waiting timer: Astra, Reply 94); a
		// cleared TIF drops its request
		m_int_pending[Z180_INT_PRT0] = (m_tcr & Z180_TCR_TIE0) && (m_tcr & Z180_TCR_TIF0);
		m_int_pending[Z180_INT_PRT1] = (m_tcr & Z180_TCR_TIE1) && (m_tcr & Z180_TCR_TIF1);
		m_int_pending[Z180_INT_CSIO] = m_csio->check_interrupt();
		m_int_pending[Z180_INT_ASCI0] = m_asci[0]->check_interrupt();
		m_int_pending[Z180_INT_ASCI1] = m_asci[1]->check_interrupt();

		for (int i = 0; i <= Z180_INT_MAX; i++)
		{
			if (m_int_pending[i])
			{
				int const cycles = take_interrupt(i);
				m_int_pending[i] = 0;
				switch (i)
				{
				case Z180_INT_ASCI0: m_asci[0]->clear_interrupt(); break;
				case Z180_INT_ASCI1: m_asci[1]->clear_interrupt(); break;
				}
				return cycles;
			}
		}
	}

	return 0;
}

/****************************************************************************
 * Handle I/O and timers
 ****************************************************************************/

void z180_device::handle_io_timers(int cycles)
{
	while (cycles-- > 0)
	{
		// FRC counts down by 1 every 10 cycles
		m_frc_prescale++;
		if (m_frc_prescale >= 10)
		{
			m_frc_prescale = 0;
			m_frc--;

			// Programmable reload timers are clocked once every 20 cycles
			if ((m_frc & 1) == 0)
				clock_timers();
		}
	}
}

// ---- upstream z180.cpp lines 2043-2077: the input lines ---------------------------------------------
void z180_device::execute_set_input(int irqline, int state)
{
	if (irqline == INPUT_LINE_NMI)
	{
		/* mark an NMI pending on the rising edge */
		if (m_nmi_state == CLEAR_LINE && state != CLEAR_LINE)
			m_nmi_pending = 1;
		m_nmi_state = state;
	}
	else
	{
		LOG("Z180 set_irq_line %d = %d\n", irqline,state);

		if(irqline == Z180_INPUT_LINE_IRQ0 || irqline == Z180_INPUT_LINE_IRQ1 || irqline == Z180_INPUT_LINE_IRQ2) {
			/* update the IRQ state */
			m_irq_state[irqline] = state;
			if(daisy_chain_present())
				m_irq_state[0] = daisy_update_irq_state();

			/* the main execute loop will take the interrupt */
		} else if(irqline == Z180_INPUT_LINE_DREQ0) {
			uint32_t iol = m_iol & ~Z180_DREQ0;
			if(state == ASSERT_LINE)
				iol |= Z180_DREQ0;
			z180_write_iolines(iol);
		} else if(irqline == Z180_INPUT_LINE_DREQ1) {
			uint32_t iol = m_iol & ~Z180_DREQ1;
			if(state == ASSERT_LINE)
				iol |= Z180_DREQ1;
			z180_write_iolines(iol);
		}
	}
}

/* logical to physical address translation */
